// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzJseyJmMDHGhO8YMrJAosgkh87DlYu7A',
    appId: '1:903345078844:web:a62ef847b0ffe76458b939',
    messagingSenderId: '903345078844',
    projectId: 'peer2peer-1dfa0',
    authDomain: 'peer2peer-1dfa0.firebaseapp.com',
    storageBucket: 'peer2peer-1dfa0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPQBNfBd3H4dBnTCtZy5CHK9PcKLibgY8',
    appId: '1:903345078844:android:ab6aaf579e97066858b939',
    messagingSenderId: '903345078844',
    projectId: 'peer2peer-1dfa0',
    storageBucket: 'peer2peer-1dfa0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPSD4WGzX2UuyN1nPkilDszQ15TdNEBlw',
    appId: '1:903345078844:ios:8e77f53896a7e78958b939',
    messagingSenderId: '903345078844',
    projectId: 'peer2peer-1dfa0',
    storageBucket: 'peer2peer-1dfa0.appspot.com',
    iosBundleId: 'com.example.letsBuy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPSD4WGzX2UuyN1nPkilDszQ15TdNEBlw',
    appId: '1:903345078844:ios:8e77f53896a7e78958b939',
    messagingSenderId: '903345078844',
    projectId: 'peer2peer-1dfa0',
    storageBucket: 'peer2peer-1dfa0.appspot.com',
    iosBundleId: 'com.example.letsBuy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzJseyJmMDHGhO8YMrJAosgkh87DlYu7A',
    appId: '1:903345078844:web:d876923d9da7bc9f58b939',
    messagingSenderId: '903345078844',
    projectId: 'peer2peer-1dfa0',
    authDomain: 'peer2peer-1dfa0.firebaseapp.com',
    storageBucket: 'peer2peer-1dfa0.appspot.com',
  );

}